"""
Slot type definitions with keyword dictionaries and regex patterns.

Each slot type maps to a graph schema entity type and provides extraction
rules: keyword matching (exact/fuzzy) and regex patterns.
"""
from typing import Dict, Any, List

SLOT_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "drug": {
        "entity_type": "Drug",
        "keywords": {
            "二甲双胍": "二甲双胍",
            "metformin": "二甲双胍",
            "格华止": "格华止",
            "阿卡波糖": "阿卡波糖",
            "拜唐苹": "拜唐苹",
            "glucobay": "拜唐苹",
            "胰岛素": "胰岛素",
            "insulin": "胰岛素",
            "二甲双胍缓释片": "二甲双胍缓释片",
            "达格列净": "达格列净",
            "恩格列净": "恩格列净",
            "利拉鲁肽": "利拉鲁肽",
            "司美格鲁肽": "司美格鲁肽",
            "ozempic": "司美格鲁肽",
            "诺和达": "诺和达",
            "氯吡格雷": "氯吡格雷",
            "阿托伐他汀": "阿托伐他汀",
            "立普妥": "立普妥",
        },
        "patterns": [
            r"(?P<drug_name>[^\s]{2,10}(?:片|胶囊|注射液|缓释片|分散片|颗粒|滴丸))",
        ],
    },
    "company": {
        "entity_type": "Company",
        "keywords": {
            "诺华": "诺华",
            "novartis": "诺华",
            "辉瑞": "辉瑞",
            "pfizer": "辉瑞",
            "拜耳": "拜耳",
            "bayer": "拜耳",
            "诺和诺德": "诺和诺德",
            "novo nordisk": "诺和诺德",
            "赛诺菲": "赛诺菲",
            "sanofi": "赛诺菲",
            "阿斯利康": "阿斯利康",
            "astrazeneca": "阿斯利康",
            "礼来": "礼来",
            "lilly": "礼来",
            "默沙东": "默沙东",
            "msd": "默沙东",
            "罗氏": "罗氏",
            "roche": "罗氏",
            "恒瑞": "恒瑞医药",
            "恒瑞医药": "恒瑞医药",
            "石药": "石药集团",
            "石药集团": "石药集团",
        },
        "patterns": [],
    },
    "channel": {
        "entity_type": "Channel",
        "keywords": {
            "零售": "零售",
            "医院": "医院",
            "线上": "线上",
            "电商": "线上",
            "OTC": "OTC",
            "处方药": "处方药",
            "基层医疗": "基层医疗",
            "社区": "基层医疗",
            "药店": "零售",
            "三甲": "三甲医院",
            "三甲医院": "三甲医院",
        },
        "patterns": [
            r"(零售|医院|线上|电商|OTC|处方药|基层医疗|社区|药店)(?:渠道|市场|终端|渠道)?",
        ],
    },
    "region": {
        "entity_type": "Region",
        "keywords": {
            "中国": "中国",
            "全国": "全国",
            "北京": "北京",
            "上海": "上海",
            "广州": "广州",
            "深圳": "深圳",
            "华东": "华东",
            "华南": "华南",
            "华北": "华北",
            "华中": "华中",
            "西南": "西南",
            "西北": "西北",
            "东北": "东北",
        },
        "patterns": [
            r"(?P<region>[一-鿿]{2,4}(?:省|市|自治区|特别行政区))",
        ],
    },
    "time_period": {
        "entity_type": "TimePeriod",
        "keywords": {},
        "patterns": [
            r"(?P<year>20\d{2})\s*年",
            r"第(?P<quarter>[一二三四1234])季度",
            r"(?P<month>\d{1,2})\s*月",
            r"(?P<year_range>20\d{2}\s*[-—至到]\s*20\d{2})\s*年?",
        ],
    },
    "indication": {
        "entity_type": "Indication",
        "keywords": {
            "糖尿病": "糖尿病",
            "diabetes": "糖尿病",
            "高血压": "高血压",
            "hypertension": "高血压",
            "高血脂": "高血脂",
            "高胆固醇": "高血脂",
            "肿瘤": "肿瘤",
            "癌症": "癌症",
            "心血管": "心血管疾病",
            "冠心病": "冠心病",
            "哮喘": "哮喘",
            "类风湿": "类风湿关节炎",
            "抑郁症": "抑郁症",
            "阿尔茨海默": "阿尔茨海默病",
            "帕金森": "帕金森病",
        },
        "patterns": [],
    },
}
