"""
Slot type definitions with keyword dictionaries and regex patterns.

Each slot type maps to a graph schema entity type and provides extraction
rules: keyword matching (exact/fuzzy) and regex patterns.
"""
from typing import Dict, Any, List

SLOT_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "product": {
        "entity_type": "Product",
        "keywords": {
            "iPhone": "iPhone",
            "iPad": "iPad",
            "MacBook": "MacBook",
            "MacBook Pro": "MacBook Pro",
            "MacBook Air": "MacBook Air",
            "iMac": "iMac",
            "Apple Watch": "Apple Watch",
            "AirPods": "AirPods",
            "HomePod": "HomePod",
            "Windows": "Windows",
            "Office": "Microsoft Office",
            "Office 365": "Microsoft 365",
            "Microsoft 365": "Microsoft 365",
            "Galaxy": "Samsung Galaxy",
            "Pixel": "Google Pixel",
            "Nexus": "Google Nexus",
            "Echo": "Amazon Echo",
            "Kindle": "Amazon Kindle",
            "PlayStation": "PlayStation",
            "Xbox": "Xbox",
            "Switch": "Nintendo Switch",
            "Tesla": "Tesla",
            "Model 3": "Tesla Model 3",
            "Model Y": "Tesla Model Y",
        },
        "patterns": [
            r"(?P<product_name>[A-Z][a-zA-Z]+(?:\s(?:Pro|Air|Max|Mini|Plus|Ultra|SE|Lite))?)(?:\s\d+)?",
        ],
    },
    "issue": {
        "entity_type": "Issue",
        "keywords": {
            "蓝屏": "蓝屏",
            "黑屏": "黑屏",
            "死机": "死机",
            "卡顿": "卡顿",
            "闪退": "闪退",
            "崩溃": "崩溃",
            "无法开机": "无法开机",
            "无法连接": "无法连接",
            "连不上网": "网络连接失败",
            "没声音": "无声音",
            "无声": "无声音",
            "充不进电": "充电异常",
            "不充电": "充电异常",
            "发热": "发热",
            "过热": "过热",
            "耗电快": "耗电异常",
            "信号差": "信号问题",
            "没信号": "信号问题",
            "无法更新": "更新失败",
            "更新失败": "更新失败",
            "无法下载": "下载失败",
            "下载失败": "下载失败",
            "安装失败": "安装失败",
            "登录失败": "登录失败",
            "无法登录": "登录失败",
            "密码错误": "密码错误",
            "账号锁定": "账号锁定",
            "数据丢失": "数据丢失",
            "同步失败": "同步失败",
            "蓝牙断连": "蓝牙断连",
            "WiFi断连": "WiFi断连",
            "触摸失灵": "触摸失灵",
            "按键失灵": "按键失灵",
            "相机故障": "相机故障",
            "电池老化": "电池老化",
            "屏幕碎裂": "屏幕碎裂",
            "扬声器故障": "扬声器故障",
            "麦克风故障": "麦克风故障",
        },
        "patterns": [
            r"(?P<issue_desc>无法.{1,6}|不能.{1,6}|总是.{1,6}|经常.{1,6}|突然.{1,6})",
        ],
    },
    "platform": {
        "entity_type": "Platform",
        "keywords": {
            "iOS": "iOS",
            "Android": "Android",
            "Windows": "Windows",
            "macOS": "macOS",
            "Linux": "Linux",
            "iPadOS": "iPadOS",
            "watchOS": "watchOS",
            "tvOS": "tvOS",
            "Chrome OS": "Chrome OS",
            "HarmonyOS": "HarmonyOS",
            "鸿蒙": "HarmonyOS",
            "Ubuntu": "Ubuntu",
            "CentOS": "CentOS",
            "Windows 10": "Windows 10",
            "Windows 11": "Windows 11",
            "Windows 7": "Windows 7",
            "Sonoma": "macOS Sonoma",
            "Ventura": "macOS Ventura",
            "Sequoia": "macOS Sequoia",
        },
        "patterns": [
            r"(?P<platform>iOS|Android|Windows|macOS|Linux|HarmonyOS|Ubuntu)\s*(?P<version>\d+(?:\.\d+)*)?",
        ],
    },
    "feature": {
        "entity_type": "Feature",
        "keywords": {
            "WiFi": "WiFi",
            "蓝牙": "蓝牙",
            "Bluetooth": "蓝牙",
            "摄像头": "摄像头",
            "Face ID": "Face ID",
            "指纹": "指纹识别",
            "Touch ID": "Touch ID",
            "NFC": "NFC",
            "GPS": "GPS",
            "5G": "5G",
            "4G": "4G",
            "LTE": "LTE",
            "快充": "快充",
            "无线充电": "无线充电",
            "面部识别": "Face ID",
            "语音助手": "语音助手",
            "Siri": "Siri",
            " iCloud": "iCloud",
            "iCloud": "iCloud",
            "Dark Mode": "深色模式",
            "深色模式": "深色模式",
            "暗黑模式": "深色模式",
            "分屏": "分屏",
            "多任务": "多任务",
            "截屏": "截屏",
            "录屏": "录屏",
            "投屏": "投屏",
            "热点": "个人热点",
            "VPN": "VPN",
            "飞行模式": "飞行模式",
            "省电模式": "低电量模式",
            "低电量模式": "低电量模式",
            "勿扰模式": "勿扰模式",
            "通知": "通知",
            "备份": "备份",
            "恢复": "恢复",
            "重置": "重置",
            "越狱": "越狱",
            "Root": "Root",
        },
        "patterns": [],
    },
    "category": {
        "entity_type": "Category",
        "keywords": {
            "硬件": "硬件",
            "软件": "软件",
            "网络": "网络",
            "账号": "账号",
            "账单": "账单",
            "支付": "支付",
            "退款": "退款",
            "物流": "物流",
            "配送": "配送",
            "售后": "售后",
            "保修": "保修",
            "维修": "维修",
            "换货": "换货",
            "退货": "退货",
            "安全": "安全",
            "隐私": "隐私",
            "设置": "设置",
            "安装": "安装",
            "升级": "升级",
            "更新": "更新",
            "备份恢复": "备份恢复",
            "性能": "性能",
            "兼容性": "兼容性",
            "驱动": "驱动",
            "固件": "固件",
            "配件": "配件",
            "电池": "电池",
            "屏幕": "屏幕",
            "存储": "存储",
            "内存": "内存",
        },
        "patterns": [],
    },
    "time_period": {
        "entity_type": "TimePeriod",
        "keywords": {},
        "patterns": [
            r"(?P<year>20\d{2})\s*年",
            r"第(?P<quarter>[一二三四1234])季度",
            r"(?P<month>\d{1,2})\s*月",
            r"(?P<year_range>20\d{2}\s*[-—至到]\s*20\d{2})\s*年?",
            r"(?P<relative>今天|昨天|前天|上周|本周|这周|上个月|这个月|最近|刚刚|刚才)",
        ],
    },
}
